import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const tareasPlantillaData = [
  {
    area: "CONTA",
    nombre: "F29",
    detalle: "Confección y envio de F29",
    frecuenciaTexto: "1 vez al mes",
    plazoMaximoTexto: "15 de cada mes",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 15,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Estado de Resultado",
    detalle: "Emitir informe en sistema, limpiar en excel",
    frecuenciaTexto: "1 vez al mes",
    plazoMaximoTexto: "25 de cada mes / sobre el mes anterior",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Simulación Impuesto Renta aplicado directo",
    detalle: "Aplicar tasa del regimen sobre Resultado antes de impuesto",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes / sobre acumulado mes anterior",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Conciliación Bancaria",
    detalle: "Conciliar",
    frecuenciaTexto: "Semanal",
    plazoMaximoTexto: "Viernes de cada semana",
    presentacion: "CLIENTE",
    frecuencia: "SEMANAL",
    diaMesVencimiento: null,
    diaSemanaVencimiento: 5,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Analisis cuentas por cobrar",
    detalle: "Cuentas por cobrar y antigüedad de las mismas",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes / sobre el mes anterior",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Analisis cuentas por Pagar",
    detalle: "Cuentas por Pagar y antigüedad de las mismas",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes / sobre el mes anterior",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Amortizaciones de creditos",
    detalle: "Tener a la vista tabla de amortizaciones para creditos vigentes",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "30 de cada mes, para el mes en curso",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 30,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Centralización F29",
    detalle: "Contabilizar las partidas involucradas en el F29",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "30 de cada mes, para el mes en curso",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 30,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Centralización cuotas creditos / Leasing",
    detalle: "Contabilizar pagos de cuotas en pasivo y resultado",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "30 de cada mes, para el mes en curso",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 30,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Centralización remunaciones",
    detalle: "Centralizar las partidas asociadas",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "5 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 5,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Cierre contabilización libro compra",
    detalle: "Contabilzación de todas las facturas RCV en ERP",
    frecuenciaTexto: "Semanal",
    plazoMaximoTexto: "5 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "SEMANAL",
    diaMesVencimiento: null,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Cierre contabilización libro Venta",
    detalle: "Contabilzación de todas las facturas RCV en ERP",
    frecuenciaTexto: "Semanal",
    plazoMaximoTexto: "5 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "SEMANAL",
    diaMesVencimiento: null,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Cierre contabilización libro Honorario",
    detalle: "Contabilización de todos los honorarios según SII",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "5 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 5,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Conciliación RCV - ERP",
    detalle: "Informe de diferencias entre RCV y ERP",
    frecuenciaTexto: "Semanal",
    plazoMaximoTexto: "5 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "SEMANAL",
    diaMesVencimiento: null,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Analisis cuenta retiro socios",
    detalle: "Detalle de los retiros efectuados por cada socio",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes / sobre el mes anterior",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Informe de cuentas de activo y pasivo con saldos invertidos",
    detalle: "Cuentas de activo con saldo acreedor, pasivos con saldo deudor",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Envio Pre-IVA",
    detalle: "Enviar pre-iva (solo debitos - Credito) según RCV",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 del mes en curso",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Envio semanal correo a cliente",
    detalle: "Comunicación para envio o solicitud de información",
    frecuenciaTexto: "Semanal",
    plazoMaximoTexto: "Semanal",
    presentacion: "CLIENTE",
    frecuencia: "SEMANAL",
    diaMesVencimiento: null,
    diaSemanaVencimiento: null, // aquí puedes luego fijar un día de la semana
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Informe observaciones SII",
    detalle: "Todos los meses informe para revisión interna (IVAS)",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Informe Deuda TGR",
    detalle: "Certificado deuda fiscal TGR para envio al cliente",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Convenios y/o postergaciones TGR",
    detalle: "Informe con pantallazos con cuotas por vencer de convenios y/o Postergaciones de impuestos.",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes",
    presentacion: "CLIENTE",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
  {
    area: "CONTA",
    nombre: "Control de Activo Fijo",
    detalle: "Mensual con detalle de activos años anteriores y en curso, revisión interna",
    frecuenciaTexto: "Mensual",
    plazoMaximoTexto: "25 de cada mes / sobre el mes anterior",
    presentacion: "INTERNO",
    frecuencia: "MENSUAL",
    diaMesVencimiento: 25,
    diaSemanaVencimiento: null,
    activo: true,
  },
] as const;

async function main() {
  await prisma.tareaPlantilla.createMany({
    data: tareasPlantillaData as any,
    skipDuplicates: true,
  });
  console.log("✅ Tareas plantilla insertadas/actualizadas");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
